@baseUrl = http://127.0.0.1:8000/api/v1

# получение постов
GET {{baseUrl}}/posts/
Content-Type: application/json

###

POST {{baseUrl}}/posts/
Content-Type: application/json

{
    "title": "Post from VS",
    "text": "Post from VSPost from VSPost from VSPost from VSPost from VS",
    "autor": "also me"
}

###

PATCH {{baseUrl}}/posts/3/
Content-Type: application/json

{
    "title": "Update",
    "text": "Update Post From VS"
}

###

GET {{baseUrl}}/posts/42/
Content-Type: application/json

###

DELETE {{baseUrl}}/posts/43/
Content-Type: application/json



###

POST {{baseUrl}}/comments/
Content-Type: application/json

{
    "autor": "tgtgtgtgtgtg",
    "text": "tgtgtgtgtgtg",
    "post_id": "34"
}